version: 2.1 # specifies the CircleCI configuration version
orbs: # pre-packaged reusable configurations and commands
  node: circleci/node@5.0.1 # orb for Node.js-related tasks
  docker: circleci/docker@2.1.4 # orb for Docker-related tasks

jobs:
  build: # the 'build' job checks out the source code, installs Node.js packages using npm, and logs the installation process.
    docker:
      - image: cimg/node:16.10 # use a CircleCI-managed Docker image with Node.js 16.10
    steps:
      - checkout # checks out the source code from your version control system (e.g., Git)
      - node/install-packages:
          pkg-manager: npm # install Node.js packages using npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test: # the 'test' job checks out the source code, installs Node.js packages using npm, and runs tests using npm. It is dependent on the build job.
    docker:
      - image: cimg/node:16.10 # Use the same Node.js Docker image for testing
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  build-and-push: # the 'build-and-push' job sets up a remote Docker environment, checks if Docker is available and configured, builds a Docker image with a specified name and tag, and pushes the image to a Docker registry. It depends on the test job.
    executor: docker/docker # use a Docker executor for this job
    steps:
      - setup_remote_docker # set up a remote Docker environment
      - checkout 
      - docker/check  # check if Docker is available and properly configured
      - docker/build: 
          image: lohcd/cd_demo_4.6 # define the Docker image name to build
          tag: 1.0.1 # define the Docker image tag to apply
      - docker/push:
          image: lohcd/cd_demo_4.6 # define the Docker image name to push
          tag: 1.0.1 # define the Docker image tag to push
workflows:
  simple_workflow:
    jobs:
      - build # execute the 'build' job
      - test:
          requires:
            - build # execute the 'test' job after 'build' is done
      - build-and-push:
          requires:
            - test # execute the 'build-and-push' job after 'test'
